import promise from './promise';
import es6 from './es6';
import objects from './objects';
import arrays from './arrays';
import anonymous from './anonymous';
import main from './varDeclaration';
promise();
es6();
objects();
arrays();
anonymous();
main();